name: "Bump Version Tag"

on:
  push:
    branches:
      - main
    paths-ignore:
      - .env.template
      - .gitignore
      - .github/renovate.json
      - .pre-commit-config.yaml
      - README.MD
      - LICENSE
      - src/mealie_mcp/__init__.py # version bumps
  workflow_dispatch:

jobs:
  bump-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Get next version
        id: version
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297 # 1.71.0
        env:
          WITH_V: true
          DEFAULT_BUMP: patch
          DRY_RUN: true

      - name: Install uv
        uses: astral-sh/setup-uv@c7f87aa956e4c323abf06d5dec078e358f6b4d04 # v6

      - name: Bump version in files
        run: |
          version="${{ steps.version.outputs.new_tag }}"
          clean_version="${version#v}"
          sed -i "s/__version__ = .*/__version__ = \"${clean_version}\"/" src/mealie_mcp/__init__.py
          sed -i "s/version = .*/version = \"${clean_version}\"/" pyproject.toml
          uv lock --upgrade-package mealie-mcp

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5
        with:
          commit_message: automated version bump

      - name: Push version tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297 # 1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_WRITE_PAT }}
          CUSTOM_TAG: ${{ steps.version.outputs.new_tag }}